### PR TITLE
Allow blocks without else.

### PR DESCRIPTION
**Pull request by clarcharr**
It doesn't seem immediately obvious from the documentation that you can't do a block without an else branch, so, I added that functionality.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Out of curiosity, do you have a use case for this? This was originally intentional because I'd consider it bad practice to not have a fallback

**Comment by clarcharr** [comment]
I mean, I make pretty extensive use of it in [len-trait](https://github.com/clarcharr/len-trait/blob/master/src/impls.rs) and it seems excessive to have to add `else {}` everywhere.

**Comment by alexcrichton** [comment]
Ah ok, that seems reasonable!

**Comment by clarcharr** [comment]
Would you be willing to push another version to crates.io for this?

**Comment by alexcrichton** [comment]
Sure, published

**Pull request merged**
