### PR TITLE
Put `#[cfg]` in backticks.

### PR DESCRIPTION
**Pull request by goffrie**
The bare `[cfg]` makes rustdoc nightly complain.

### CODE REVIEW

**Comment by Thomasdezeeuw** [comment]
With the current nightly it won't even document the crate, could this be merged?

**Comment by gnzlbg** [comment]
alex will be back at the end of the month, this will have to wait until then, sorry for the inconvenience

**Comment by gnzlbg** [comment]
@goffrie thank you for the PR. The other PRs also bumps the version and it will be quicker to merge that one and just do a new release afterwards. Would you be willing to close this PR so that there is only one about this issue open? (might help speed things up once alex is back, his TODO list will be... pretty large...).

**Comment by Thomasdezeeuw** [comment]
For anyone who want the create docs in the meantime `cargo doc --no-deps` will document only your own crate.

**Pull request closed without merging**
